ScrollReveal().reveal('.cta', { delay: 500 });
ScrollReveal().reveal('.cards', { delay: 500 });
ScrollReveal().reveal('#products', { delay: 500 });
ScrollReveal().reveal('.video', { delay: 500 });
ScrollReveal().reveal('.information', { delay: 500 });
ScrollReveal().reveal('.questions', { delay: 500 });
ScrollReveal().reveal('.map', { delay: 500 });
ScrollReveal().reveal('.contact-data', { delay: 500 });
ScrollReveal().reveal('.footer', { delay: 500 });